import { useState } from "react";
import type { FormEvent } from "react";
import { extractErrorMessage } from "../../api/errors";
import type { CreateTutorInput, Tutor } from "../../types/tutor";

export function TutorForm({ initialData, onSubmit, onCancel }: { initialData?: Tutor; onSubmit: (input: CreateTutorInput) => Promise<unknown>; onCancel: () => void }) {
  const [form, setForm] = useState<CreateTutorInput>({ name: initialData?.name ?? "", documentType: initialData?.documentType ?? "CPF", document: initialData?.document ?? "", rg: initialData?.rg ?? "", phone: initialData?.phone ?? "", email: initialData?.email ?? "", street: initialData?.street ?? "", number: initialData?.number ?? "", complement: initialData?.complement ?? "", neighborhood: initialData?.neighborhood ?? "", city: initialData?.city ?? "", state: initialData?.state ?? "", zipCode: initialData?.zipCode ?? "" });
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const field = (name: keyof CreateTutorInput, label: string, required = true, type = "text") => <div><label className="mb-1 block text-sm font-medium text-slate-700">{label}</label><input type={type} required={required} value={String(form[name] ?? "")} onChange={(event) => setForm({ ...form, [name]: event.target.value })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /></div>;
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { await onSubmit(form); } catch (err) { setError(extractErrorMessage(err, "Erro ao salvar tutor")); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 md:grid-cols-2">{field("name", "Nome completo / Razão social") }<div><label className="mb-1 block text-sm font-medium text-slate-700">Tipo de documento</label><select value={form.documentType} onChange={(event) => setForm({ ...form, documentType: event.target.value as "CPF" | "CNPJ" })} className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="CPF">CPF</option><option value="CNPJ">CNPJ</option></select></div>{field("document", "CPF / CNPJ")}{field("rg", "RG", false)}{field("phone", "Telefone")}{field("email", "E-mail", true, "email")}</div><p className="border-t pt-4 text-sm font-semibold text-slate-700">Endereço</p><div className="grid gap-4 md:grid-cols-3">{field("street", "Rua", true)}{field("number", "Número")}{field("complement", "Complemento", false)}{field("neighborhood", "Bairro")}{field("city", "Cidade")}{field("state", "UF")}{field("zipCode", "CEP")}</div>{error && <p className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2 text-sm text-slate-600 hover:bg-slate-100">Cancelar</button><button disabled={saving} className="rounded-lg bg-teal-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{saving ? "Salvando..." : "Salvar tutor"}</button></div></form>;
}
